# Generated by Django 6.0.4 on 2026-04-22 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Letters and digits only [a-zA-z0-9]', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('home_page', models.URLField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='idx_users_email'), models.Index(fields=['username'], name='idx_users_username')],
                'constraints': [models.UniqueConstraint(fields=('username', 'email'), name='unique_user_identity')],
            },
        ),
    ]
